sims/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('lounge/', include('simslounge.urls'))
]

simslounge/urls.py
from django.urls import path

from . import views

app_name='simslounge'
urlpatterns = [
    path('', views.index, name='index'),
    path('voteform/<int:proposal_id>', views.vote_form, name='voteform'),
    path('vote/<int:proposal_id>', views.vote, name='vote'),
    path('proposals/<int:lounge_id>', views.view_proposals, name='proposals'),
    path('login', views.login_handle, name='login'),
    path('login_page', views.login_page, name='login_page'),
    path('mylounges', views.my_lounges, name='my_lounges'),
    path('createproposal/<int:lounge_id>', views.create_proposal, name='createproposal'),
    path('proposalform/<int:lounge_id>', views.proposal_form, name='proposalform'),
    path('logout', views.logout_handle, name='logout'),
]

simslounge/models.py
from django.db import models
from django.contrib.auth.models import User

class Lounge(models.Model):
    lounge_name = models.CharField(max_length=200)
    lounge_description = models.TextField(blank=True, null=True)
    lounge_rep_1 = models.CharField(max_length=200)
    lounge_rep_2 = models.CharField(max_length=200, blank=True, null=True)
    lounge_url = models.URLField(max_length=200, blank=True, null=True)
    lounge_funds = models.IntegerField()
    interlounge_funds = models.IntegerField()

    def __str__(self):
        return self.lounge_name

class LoungeMember(models.Model):
    lounge = models.ForeignKey("Lounge", models.CASCADE, related_name="members")
    resident = models.ForeignKey("Resident", models.CASCADE, related_name="memberships")
    funding = models.IntegerField()

    def __str__(self):
        return self.resident.resident_name + " - " + self.lounge.lounge_name


class Resident(models.Model):
    resident_name = models.CharField(max_length=200)
    resident_title = models.CharField(max_length=200, blank=True, null=True)
    resident_kerb = models.CharField(max_length=20)
    resident_funding = models.IntegerField()
    resident_user = models.OneToOneField(User, models.SET_NULL, related_name="resident", blank=True, null=True)

    def __str__(self):
        return self.resident_name



class Proposal(models.Model):
    proposal_name = models.CharField(max_length=50)
    proposal_description = models.TextField(blank=True, null=True)
    proposal_amount = models.IntegerField()
    proposal_lounge = models.ForeignKey("Lounge", models.CASCADE, related_name="proposals")
    proposal_creator = models.ForeignKey("Resident", models.SET_NULL, null=True)
    proposal_yes = models.ManyToManyField("LoungeMember", related_name="yes_votes", blank=True, null=True)
    proposal_no = models.ManyToManyField("LoungeMember", related_name="no_votes", blank=True, null=True)
    proposal_reg_funding = models.BooleanField()
    proposal_passed = models.BooleanField()

    def __str__(self):
        return self.proposal_name

simslounge/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404, HttpResponseRedirect
from .models import Lounge, LoungeMember, Resident, Proposal
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout

# Helper Functions

def check_lounge_membership(user, lounge_id):
    # Returns whether a user in a lounge and the appropriate lounge membership
    in_lounge = False
    desired_lounge_membership = None
    for lounge_membership in user.resident.memberships.all():
        lounge = lounge_membership.lounge
        if (lounge.id == lounge_id):
            in_lounge = True
            desired_lounge_membership = lounge_membership
            break
    return (in_lounge, desired_lounge_membership)

def has_voted(membership, proposal):
    if membership in proposal.proposal_yes.all():
        return True
    elif membership in proposal.proposal_no.all():
        return True
    else:
        return False

def check_pass(proposal, lounge):
    threshold = max(len(lounge.members.all()), 5)
    if len(proposal.proposal_yes.all()) >= threshold:
        return True
    else:
        return False

def get_used_funds(lounge):
    used = 0
    for proposal in lounge.proposals.all():
        if proposal.proposal_passed:
            used += proposal.proposal_amount
    return used

def index(request):
    return HttpResponse("Hello, world.")

# Submission API

def vote(request, proposal_id):
    proposal = get_object_or_404(Proposal, pk=proposal_id)
    vote = request.POST['vote']
    if request.user.is_authenticated:
        proposal = get_object_or_404(Proposal, pk=proposal_id)
        proposal_lounge = proposal.proposal_lounge
        in_lounge, lounge_membership = check_lounge_membership(request.user, proposal_lounge.id)
        if in_lounge and not has_voted(request.user, proposal):
            if vote == "Yes":
                proposal.proposal_yes.add(lounge_membership)
                if check_pass(proposal, proposal_lounge):
                    proposal.proposal_passed = True
            else:
                proposal.proposal_no.add(lounge_membership)
    proposal.save()
    #update number with lounge id
    return HttpResponseRedirect(reverse('simslounge:proposals', args=(1,)))

def create_proposal(request, lounge_id):
    lounge = get_object_or_404(Lounge, pk=lounge_id)
    if request.user.is_authenticated:
        in_lounge, lounge_membership = check_lounge_membership(request.user, lounge.id)
        if in_lounge:
            name = request.POST['name']
            description = request.POST['description']
            amount = request.POST['amount']
            ilef = request.POST['ilef']
            reg_funding = True
            if ilef == "Yes":
                reg_funding = False
            new_proposal = Proposal(proposal_name=name, proposal_description=description, proposal_amount=amount, proposal_passed=False, proposal_lounge=lounge, proposal_reg_funding=reg_funding, proposal_creator=request.user.resident)
            new_proposal.save()
    return HttpResponseRedirect(reverse('simslounge:proposals', args=(1,)))

def join_lounge(request):
    pass

def create_lounge(request):
    pass


# Form API

def proposal_form(request, lounge_id):
    if request.user.is_authenticated:
        lounge = get_object_or_404(Lounge, pk=lounge_id)
        in_lounge, lounge_membership = check_lounge_membership(request.user, lounge.id)
        if in_lounge:
            return render(request, 'simslounge/newproposal.html', {'lounge': lounge})
        else:
            return HttpResponseRedirect(reverse('simslounge:mylounges'))
    else:
        return HttpResponseRedirect(reverse('simslounge:login_page'))

def vote_form(request, proposal_id):
    if request.user.is_authenticated:
        proposal = get_object_or_404(Proposal, pk=proposal_id)
        proposal_lounge = proposal.proposal_lounge
        in_lounge, lounge_membership = check_lounge_membership(request.user, proposal_lounge.id)
        if in_lounge and not has_voted(lounge_membership, proposal):
            return render(request, 'simslounge/vote.html', {'proposal': proposal})
        else:
            return render(request, 'simslounge/alreadyvoted.html')
    else:
        return HttpResponseRedirect(reverse('simslounge:login_page'))

def lounge_form(request):
    pass

def lounge_create_form(request):
    pass

# Standard Page API

def view_proposals(request, lounge_id):
    if request.user.is_authenticated:
        in_lounge, membership = check_lounge_membership(request.user, lounge_id)
        if in_lounge:
            lounge = get_object_or_404(Lounge, pk=lounge_id)
            proposals = lounge.proposals.all()
            used_funds = get_used_funds(lounge)
            remaining_funds = lounge.lounge_funds - used_funds
            return render(request, 'simslounge/proposals_lounge.html', {'proposals': proposals, 'lounge': lounge, 'funds_used': used_funds, 'funds_remaining': remaining_funds})
    else:
        return HttpResponseRedirect(reverse('simslounge:login_page'))

def all_proposals(request):
    proposals = Proposals.objects.all()
    return render(request, 'simslounge/proposals.html', {'proposals': proposals})

def my_lounges(request):
    if request.user.is_authenticated:
        lounge_memberships = request.user.resident.memberships
        lounges = []
        for membership in lounge_memberships.all():
            lounges.append(membership.lounge)
        return render(request, 'simslounge/mylounges.html', {'lounges': lounges, 'user': request.user})
    else:
        return HttpResponseRedirect(reverse('simslounge:login_page'))

# Authentication

def login_page(request):
    return render(request, 'simslounge/login.html')

def login_handle(request):
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(request, username=username, password=password)
    if user is not None:
        login(request, user)
        return HttpResponseRedirect(reverse('simslounge:my_lounges'))
    else:
        return HttpResponseRedirect(reverse('simslounge:login_page'))

def logout_handle(request):
    logout(request)
    return HttpResponseRedirect(reverse('simslounge:login_page'))

simslounge/templates/simslounge/alreadyvoted.html
You've already voted! <p><a href="{% url 'simslounge:my_lounges' %}">Home</a></p>

simslounge/templates/simslounge/login.html
<h1>Login Page</h1>
<form action="{% url 'simslounge:login' %}" method="post">
{% csrf_token %}
    Username: <input type="text" name="username" id="username">
    Password: <input type="password" name="password" id="password">
<input type="submit" value="Login">
</form>

simslounge/templates/simslounge/mylounges.html
Hello, {{ user.first_name }}.

<h1>Lounges</h1>

{% for lounge in lounges %}
    <a href="{% url 'simslounge:proposals' lounge.id %}">{{ lounge.lounge_name }}</a>
{% endfor %}

simslounge/templates/simslounge/newproposal.html
<h1>Proposal Creation Page</h1>
<form action="{% url 'simslounge:createproposal' lounge.id %}" method="post">
{% csrf_token %}
    <p>Proposal name: <input type="text" name="name"></p>
    <p>Description:<input type="text" name="description"></p>
    <p>Amount:<input type="text" name="amount"></p>
    <p>ILEF:</p>
    <input type="radio" name="ilef" id="yes" value="Yes">
    <label for="yes">Yes</label><br>
    <input type="radio" name="ilef" id="no" value="No">
    <label for="no">No</label>
<input type="submit" value="Submit">
</form>

simslounge/templates/simslounge/proposals.html
<h1>Proposals</h1>

{% for proposal in proposals %}
    <a href="{% url 'simslounge:voteform' proposal.id %}">{{ proposal.proposal_name }}</a>
{% endfor %}

simslounge/templates/simslounge/proposals_lounge.html
<h1>Lounge Page</h1>

<p>Lounge: {{ lounge.lounge_name }}</p>
<p>Funds Allocated: ${{ lounge.lounge_funds}}</p>
<p>Funds Used: ${{ funds_used }}</p>
<p>Funds Remaining: ${{ funds_remaining }}</p>

<p><a href="{% url 'simslounge:proposalform' lounge.id %}">New Proposal</a></p>

<h2>Proposals</h2>

{% for proposal in proposals %}
    <p><a href="{% url 'simslounge:voteform' proposal.id %}">{{ proposal.proposal_name }}</a></p>
{% endfor %}

simslounge/templates/simslounge/vote.html
<h1>Proposal Voting Page</h1>
<p>Proposal: {{ proposal.proposal_name }}</p>
<p>Proposal Description: {{ proposal.proposal_description }}</p>
<p>Do you approve of this proposal? Your selection below is your official vote and cannot be changed.</p>
<form action="{% url 'simslounge:vote' proposal.id %}" method="post">
{% csrf_token %}
    <input type="radio" name="vote" id="yes" value="Yes">
    <label for="yes">Yes</label><br>
    <input type="radio" name="vote" id="no" value="No">
    <label for="no">No</label><br>
<input type="submit" value="Vote">
</form>